blog/urls.py
from django.urls import path
from .views import (
    BlogDetailView,
    IndexView,
    CategoryView,
    CommentCreate,
    NewBlogView
)


app_name = 'blog'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('new/', NewBlogView.as_view(), name='new'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('category/<str:category>/', CategoryView.as_view(), name='category'),
    path('comment/create/<int:pk>', CommentCreate.as_view(), name='comment_create')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField('カテゴリー名', max_length=50)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField('タイトル', max_length=50)
    text = models.TextField('テキスト')
    created_at = models.DateField('作成日', auto_now_add=True)
    updated_at = models.DateField('更新日', auto_now=True)
    category = models.ForeignKey(
        Category, verbose_name='カテゴリー',
        on_delete=models.PROTECT
    )
    created_at = models.DateField('作成日', auto_now_add=True)
    updated_at = models.DateField('更新日', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'ブログ'
        verbose_name_plural = 'ブログ'


class Comment(models.Model):
    text = models.TextField('本文')
    target = models.ForeignKey(
        Blog, on_delete=models.CASCADE,
        verbose_name='対象記事'
        )

blog/forms.py
from django import forms
from .models import Comment, Blog


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class NewBlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text', 'category')

blog/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.base import View
from .models import Blog, Category, Comment
from .forms import CommentCreateForm, NewBlogForm
from django.views.generic import DetailView, ListView, CreateView
from django.urls import reverse_lazy

# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         queryset = Blog.objects.order_by('-id')
#         return render(request, 'blog/index.html', {
#             'blog': 
#         })


class IndexView(ListView):
    model = Blog
    template_name = 'blog/index.html'
    
    def get_queryset(self):
        queryset = Blog.objects.order_by('-id')
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentCreateForm
        return context


class NewBlogView(CreateView):
    template_name = 'blog/create.html'
    form_class = NewBlogForm
    success_url = reverse_lazy('blog:home')

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)


class CategoryView(ListView):
    model = Blog
    template_name = 'blog/index.html'

    def get_queryset(self):
        category = Category.objects.get(name=self.kwargs['category'])
        queryset = Blog.objects.order_by('-id').filter(category=category)
        return queryset
# categoryの

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_key'] = self.kwargs['category']
        context['comment_form'] = CommentCreateForm
        return context
# contextとしてindex.htmlで{{ category_key }}のように変数として持っていくことができる


class CommentCreate(CreateView):
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        blog_pk = self.kwargs.get('pk')
        blog = get_object_or_404(Blog, pk=blog_pk)
        comment = form.save(commit=False)
        comment.target = blog
        comment.save()

        return redirect('blog:detail', pk=blog_pk)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>blog</title>
    
</head>
<body>
    
    {% block main %}
        
    {% endblock main %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/blog/create.html
<div class="container">
    <h3>新規コメント</h3>
<form action="{% url 'blog:new' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>formの所</p>
    <div>
        <button type="submit">送信</button>
    </div>
</form>
</div>

templates/blog/detail.html
{% extends "base.html" %}
{% block main %}
<h1>詳細画面</h1>
<div class="container">
    <div class="row">            
        <hr>
        <h3>{{ blog.title }}</h3>
        <h5>content</h5>
        <p> {{ blog.text }}</p>
        <p>{{ blog.created_at }}</p>
        <hr>
    </div>
</div>

<div class="container">
    <h2>コメント</h2>
    <p>ここのfor comment in blog.comment_set.all()</p>
    <p>は1対多の時に取得するために使う</p>
    {% for comment in blog.comment_set.all %}
    
    <hr>
    <div class="comment-text">
        
        <p>{{ comment.text }}</p>
    </div>
    {% endfor %}
</div>
<hr>

<div class="container">
    <h3>新規コメント</h3>
<form action="{% url 'blog:comment_create' blog.pk%}" method="post">
    {% csrf_token %}
    {{ comment_form }}
    <div>
        <button type="submit">送信</button>
    </div>
</form>


<a href="{% url 'blog:home' %}" class="pt-3">homeに戻る</a>
</div>

{% endblock main %}

templates/blog/index.html
{% extends "base.html" %}
{% block main %}
    <h3 class="">HOME</h3>
    <hr>

    <div class="container">
        <div class="row">
            <a class="col-2" href="{% url 'blog:home' %}"><p>トップ</p></a>
            <a href="{% url 'admin:index' %}" class="col-2">管理画面へ</a>
            <a href="{% url 'blog:new' %}" class="col-2">新規投稿</a>
        </div>
    </div>
    <hr>
<div class="container">
    <div class="row">
        <div>
            <h4>カテゴリー</h4>
            <!-- context.pyのオブジェクトを取得しています。（category_list）-->
            {% for category in category_list %}
            <a href="{% url 'blog:category' category.name %}">
                <p>{{ category.name }}</p>
            </a>
            {% endfor %}
        </div>
        <br>
    </div>
</div>
    <!-- 上記のfloatスタイルの影響を受けないようにしている。（clear）-->
    <h1>一覧</h1>
    <br>
<!-- <h1>なぜかカテゴリー一覧が表示されない</h1> -->

    {% if category_key %}
        <h3>カテゴリー：{{ category_key }}</h3>
    {% else %}
    <h3>カテゴリ選択で指定できます</h3>
    {% endif %}


    {% for item in object_list %} 
    <div class="container">
        <div class="row">            
            <h5 class="">title</h5>
            <p>{{ item.title }}</p>
            <h5>content</h5>
            <p>{{ item.text }}</p>
        </div>
        <a href="{% url 'blog:detail' item.pk %}">詳細</a>
    </div>
    <hr>
    {% endfor %}
{% endblock main %}